---
title: "Talleres Finanzas Sostenibles Cuantitativas"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plantillas

- Plantilla para argumentos semanales
   - [Archivo fuente](Plantillas/Argumento.Rmd)
   - [Presentación](Plantillas/Presentacion.Rmd)
   - [Base de datos bibliografía](Plantillas/referencias.bib)
   - [Base de datos figura](Plantillas/data.RData)
   - [PDF resultante del compilar archivo fuente](/Plantillas/Argumento.pdf)

## Taller 1 

- [Proyecto 4](https://www.core-econ.org/doing-economics/book/text/04-03.html) de [coreecon](http://core-econ.org)
  - [Script en formato Markdown](Taller1/Doing-Economics-Project-4-R-Markdown.Rmd)
  - [Datos Naciones Unidas](Taller1/Download-GDPconstant-USD-countries.xlsx)
  
## Taller 2
  
- [Proyecto 5](https://www.core-econ.org/doing-economics/book/text/05-03.html) de [coreecon](http://core-econ.org)
  - [Script en formato Markdown por traducir]()
- [Desigualdad en América Latina](Taller2/WelfareIneqLatam.Rmd)


## Taller 3

- [Diagramas](Taller3/Diagramas.Rmd)

## Taller 4

- [ETL Bienestar Chile](../Taller4/Chile.Rmd)

## Taller 5

- [Cómputo simbólico](Taller5/Verifications.Rmd)

## Taller 6

- [Nubes de palabras](Taller6/WordCloud.Rmd)

## Taller 7

- [Scraping](Taller7/Scraping.Rmd)

## Taller 8

- [Pareto Distribution](Taller8/Pareto.Rmd)
